config/routes.rb
NewMusic::Application.routes.draw do
  devise_for :users

  resources :generations

  resources :songs do
    resources :rules
  end

  match "/songs/:id/step" => "songs#step", via: [:get], as: "song_step"

  authenticated :user do
    root to: 'songs#index'
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/generation.rb
# == Schema Information
#
# Table name: generations
#
#  id         :integer          not null, primary key
#  current    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  song_id    :integer
#

class Generation < ActiveRecord::Base
  belongs_to :song

  validates_length_of :current, minimum: 14, maximum: 14, allow_blank: false

  attr_accessible :current

  def self.first_generation_string
    "00000000000000"
  end

end

app/controllers/generations_controller.rb
class GenerationsController < ApplicationController
  load_and_authorize_resource

  # GET /generations
  # GET /generations.json
  def index
    @generations = Generation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @generations }
    end
  end

  # GET /generations/1
  # GET /generations/1.json
  def show
    @generation = Generation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @generation }
    end
  end

  # GET /generations/new
  # GET /generations/new.json
  def new
    @generation = Generation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @generation }
    end
  end

  # GET /generations/1/edit
  def edit
    @generation = Generation.find(params[:id])
  end

  # POST /generations
  # POST /generations.json
  def create
    @generation = Generation.new(params[:generation])

    respond_to do |format|
      if @generation.save
        format.html { redirect_to @generation, notice: 'Generation was successfully created.' }
        format.json { render json: @generation, status: :created, location: @generation }
      else
        format.html { render action: "new" }
        format.json { render json: @generation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /generations/1
  # PUT /generations/1.json
  def update
    @generation = Generation.find(params[:id])

    respond_to do |format|
      if @generation.update_attributes(params[:generation])
        format.html { redirect_to @generation, notice: 'Generation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @generation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generations/1
  # DELETE /generations/1.json
  def destroy
    @generation = Generation.find(params[:id])
    @generation.destroy

    respond_to do |format|
      format.html { redirect_to generations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/generations_helper.rb
module GenerationsHelper
end

app/views/generations/_form.html.erb
<%= form_for(@generation) do |f| %>
  <% if @generation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generation.errors.count, "error") %> prohibited this generation from being saved:</h2>

      <ul>
      <% @generation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :current %><br />
    <%= f.text_field :current %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generations/_generation.html.haml
= div_for generation do
  - generation.current.split("").each_with_index do |cell, i|
    .cell{ data: {gid: generation.id, num: i, active: cell == "1" ? "true" : "false"}, class: cell == "1" ? "active" : "" }

app/views/generations/edit.html.erb
<h1>Editing generation</h1>

<%= render 'form' %>

<%= link_to 'Show', @generation %> |
<%= link_to 'Back', generations_path %>

app/views/generations/index.html.erb
<h1>Listing generations</h1>

<table>
  <tr>
    <th>Current</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @generations.each do |generation| %>
  <tr>
    <td><%= generation.current %></td>
    <td><%= link_to 'Show', generation %></td>
    <td><%= link_to 'Edit', edit_generation_path(generation) %></td>
    <td><%= link_to 'Destroy', generation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Generation', new_generation_path %>

app/views/generations/new.html.erb
<h1>New generation</h1>

<%= render 'form' %>

<%= link_to 'Back', generations_path %>

app/views/generations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Current:</b>
  <%= @generation.current %>
</p>


<%= link_to 'Edit', edit_generation_path(@generation) %> |
<%= link_to 'Back', generations_path %>