config/routes.rb
NewMusic::Application.routes.draw do
  devise_for :users

  resources :generations

  resources :songs do
    resources :rules
  end

  match "/songs/:id/step" => "songs#step", via: [:get], as: "song_step"

  authenticated :user do
    root to: 'songs#index'
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  key        :string(255)      default("CM")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ActiveRecord::Base
  has_many :generations
  has_many :rules
  belongs_to :user

  attr_accessible :key, :title

  after_create :initialize_first_generation
  after_create :initialize_base_rules

  def initialize_first_generation
    self.generations.create!(current: Generation.first_generation_string)
  end

  def initialize_base_rules
    self.rules.create(to_match: "0", new_cell: "0")
    self.rules.create(to_match: "1", new_cell: "1")
  end

  def step
    current_gen = self.generations.last.current
    new_gen = ""
    
    current_gen.length.times do |i|

      self.rules.long_first.each do |rule|
        if rule.match(current_gen, i)
          new_gen += rule.new_cell
          break
        end
      end

    end

    self.generations.create(current: new_gen)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  load_and_authorize_resource

  def index
    @songs = current_user.songs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  def show
    @song = Song.find(params[:id])
    @rules = @song.rules.old_first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # def edit
  #   @song = Song.find(params[:id])
  # end

  def create
    @song = current_user.songs.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  def step
    @song = Song.find(params[:id], include: [ :rules ])
    num_gens = params[:generations_per_step].to_i

    @new_generations = []

    num_gens.times do
      @new_generations << @song.step
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
  def pretty_key(key)
    return "No key set" if key.nil?

    ret = key[0]

    ret += " Minor" if key[1] == "m"
    ret += " Major" if key[1] == "M"
    ret += " Harmonic" if key[1] == "h"

    ret
  end
end

app/views/songs/_form.html.haml
= form_for(song) do |f|

  /% if @song.errors.any? %>
  / <div id="error_explanation">
  /   <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

  /   <ul>
  /   <% @song.errors.full_messages.each do |msg| %>
  /     <li><%= msg %></li>
  /   <% end %>
  /   </ul>
  / </div>
  /% end %>

  %br

  .field
    = f.label :title
    = f.text_field :title

  .actions
    = f.submit "Create Song", class: "btn btn-success"

app/views/songs/_song.html.haml
.song.clearfix
  %h1= song.title
  .song-info.pull-right
    .song-item.label.label-warning= pretty_key song.key
    .song-item.label.label-success= "#{pluralize(song.generations.size, "generation")}"

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.haml
.well
  .song-actions
    = link_to new_song_path, class: "pull-right btn btn-large btn-primary" do
      %i.icon-plus.icon-white
      New Song

  .songs-list.clear
    - if @songs.present?
      - @songs.each do |song|
        = link_to song do
          = render song
    - else
      %h2 You don't have any songs yet :(

app/views/songs/new.html.haml
.well
  %h1 New song
  
  = render 'form', song: @song

app/views/songs/show.html.haml
.well.clearfix
  .song-show-title
    %h1= @song.title

  .song-show-container
    .song-show-content.pull-left
      .song-show-keynotes.clearfix
        - 14.times do |i|
          .key-note{ data: { keynum: i } }

      .song-show-generations.clearfix
        - @song.generations.each do |generation|
          = render generation, generation: generation

      .actions.clear
        = link_to "#", class: "btn btn-primary", id: "play-btn" do
          %i.icon-play.icon-white
          Play

        = link_to "#", class: "btn btn-success pull-right", id: "step-btn", data: {sid: @song.id} do
          %i.icon-music.icon-white
          Step

    .song-show-info.pull-right
      .info-field
        = link_to "#rulebook-modal", class: "btn btn-large btn-warning", id: "open-rulebook-btn", data: { toggle: "modal" } do
          %i.icon-book.icon-white
          Open Rulebook

      .info-field.clearfix.key-info
        Key
        = select(:song, :key, [["A Major", "AM"], ["A Minor", "Am"], ["A Harmonic", "Ah"], ["B Major", "BM"], ["B Minor", "Bm"], ["C Major", "CM"], ["C Minor", "Cm"], ["D Major", "DM"], ["D Minor", "Dm"], ["E Major", "EM"], ["E Minor", "Em"], ["F Major", "FM"], ["F Minor", "Fm"], ["G Major", "GM"], ["G Minor", "Gm"] ], {}, { class: "pull-right", data: { sid: @song.id } } )

      .info-field.clearfix.mapping-info
        Mapping
        = select_tag(:mapping, options_for_select([["Cell row to pitch", "pitch"], ["Cell row to pitch with binary sum", "sum"], ["Cell to note", "note"]], 0), { class: "pull-right" })

      .info-field.clearfix.gen-per-step-info
        Generation(s) Per Step
        = select_tag(:generations_per_step, options_for_select([[1,1], [2,2], [3,3], [4,4], [5,5], [10,10], [20, 20]], 0), { class: "pull-right"} )

#rulebook-modal.modal.hide.fade.clearfix
  .modal-header.clearfix
    %h3
      Define Your Cell Rules
      = link_to "#", class: "pull-right", data: { dismiss: "modal"} do
        %i.icon-remove

  .modal-body.clearfix
    .rules-list
      - @rules.each do |rule|
        = render rule

  .modal-footer.clearfix
    = link_to "#", class: "btn btn-success", id: "new-rule-btn", data: { sid: @song.id } do
      %i.icon-plus.icon-white
      New Rule

app/views/songs/step.js.erb
<% @new_generations.each do |generation| %>
  $(".song-show-generations").append($("<%= j render generation %>").hide().fadeIn(300));
  $("#step-btn").removeAttr("disabled");
<% end %>