config/routes.rb
NewMusic::Application.routes.draw do
  devise_for :users

  resources :generations

  resources :songs do
    resources :rules
  end

  match "/songs/:id/step" => "songs#step", via: [:get], as: "song_step"

  authenticated :user do
    root to: 'songs#index'
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/rule.rb
# == Schema Information
#
# Table name: rules
#
#  id         :integer          not null, primary key
#  to_match   :string(255)
#  new_cell   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  song_id    :integer
#

class Rule < ActiveRecord::Base
  belongs_to :song

  scope :long_first, order('length(to_match) DESC')
  scope :old_first, order("created_at ASC")  

  attr_accessible :new_cell, :to_match

  def match(current_gen, i)
    len = self.to_match.length
    chars_to_match = []

    len.times do |c_len|
      # center rule around i
      c_len = c_len - len / 2
      num_to_add = c_len + i

      num_to_add  = current_gen.length + num_to_add if i < 0
      num_to_add = num_to_add - current_gen.length if num_to_add >= current_gen.length

      chars_to_match << current_gen[num_to_add]
    end

    ret = true

    chars_to_match.each_with_index do |ch, i|

      if to_match[i] != ch
        ret = false
        break
      end
    end

    ret
  end

  def update_neighborhood_size(new_size)
    current_size = to_match.length

    difference = (new_size - current_size).abs
    if new_size > current_size
      padding = "0" * (difference / 2)
      self.to_match = "#{padding}#{self.to_match}#{padding}"
    elsif current_size > new_size
      self.to_match = self.to_match[(difference / 2)...(current_size - difference / 2)]
    end

    save!
  end

  def self.max_rule_length
    7
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  load_and_authorize_resource :song
  load_and_authorize_resource :rule, through: :song

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rules }
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @rule = Rule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/new
  # GET /rules/new.json
  def new
    @rule = Rule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/1/edit
  def edit
    @rule = Rule.find(params[:id])
  end

  # POST /rules
  # POST /rules.json
  def create
    @song = Song.find(params[:song_id])
    @rule = @song.rules.new(params[:rule])

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render json: @rule, status: :created, location: @rule }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rules/1
  # PUT /rules/1.json
  def update
    @song = Song.find(params[:song_id])
    @rule = @song.rules.find(params[:id])

      if params[:rule][:neighborhood_size].present?
        @rule.update_neighborhood_size(params[:rule][:neighborhood_size].to_i)
      else
        @rule.update_attributes(params[:rule])
      end

    respond_to do |format|
      format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
      format.json { head :no_content }
      format.js
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @song = Song.find(params[:song_id])
    @rule = @song.rules.find(params[:id])
    @rule.destroy
    @destroyed_id = params[:id]

    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to_match %><br />
    <%= f.text_field :to_match %>
  </div>
  <div class="field">
    <%= f.label :new_cell %><br />
    <%= f.text_field :new_cell %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/_rule.html.haml
- editable = rule.to_match.length > 1

.overall-rule{ class: editable ? "clear clearfix" : "clearfix first-two", data: {rid: rule.id}}
  = div_for rule, class: editable ? "clearfix clear" : "clearfix first-two" do
    .tomatch-row.clearfix
      - rule.to_match.split("").each_with_index do |rcell, i|
        .rcell{ data: {sid: rule.song.id, rid: rule.id, num: i, active: rcell == "1" ? "true" : "false", editable: "#{editable}"}, class: rcell == "1" ? "rcell_active" : "" }

    - padding = rule.to_match.length / 2
    .arrow-row.clearfix
      - padding.times do |i|
        .rpadding
      .rule-arrow.pull-left
        %i.icon-arrow-down
      
    .new-cell-row.clearfix
      - padding.times do |i|
        .rpadding
      .rnewcell{ data: {sid: rule.song.id, rid: rule.id, active: rule.new_cell == "1" ? "true" : "false" }, class: rule.new_cell == "1" ? "rnewcell_active" : "" }

  -if editable
    .rule-info
      .rule-size-info
        Neighborhood Size
        %br
        = select_tag(:"neighborhood_size_#{rule.id}", options_for_select([[3,3], [5,5], [7,7]], rule.to_match.length), { data: { sid: rule.song.id, rid: rule.id } } )


      .rule-delete
        = link_to "#", class: "btn btn-danger delete-rule-btn", data: { sid: rule.song.id, rid: rule.id } do
          %i.icon-trash.icon-white

app/views/rules/create.js.erb
$(".rules-list").append("<%= j render @rule %>");
$("#new-rule-btn").removeAttr("disabled");
$("#rulebook-modal").scrollTop($("#rulebook-modal")[0].scrollHeight);
rule_margin_fix();

app/views/rules/destroy.js.erb
$(".overall-rule[data-rid=<%= @destroyed_id %>]").remove();

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1>Listing rules</h1>

<table>
  <tr>
    <th>To match</th>
    <th>New cell</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rules.each do |rule| %>
  <tr>
    <td><%= rule.to_match %></td>
    <td><%= rule.new_cell %></td>
    <td><%= link_to 'Show', rule %></td>
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>To match:</b>
  <%= @rule.to_match %>
</p>

<p>
  <b>New cell:</b>
  <%= @rule.new_cell %>
</p>


<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>

app/views/rules/update.js.erb
$(".overall-rule[data-rid=<%= @rule.id %>]").replaceWith("<%= j render @rule %>");
rule_margin_fix();