config/routes.rb
NewMusic::Application.routes.draw do
  devise_for :users

  resources :generations

  resources :songs do
    resources :rules
  end

  match "/songs/:id/step" => "songs#step", via: [:get], as: "song_step"

  authenticated :user do
    root to: 'songs#index'
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 1D Music

    %link{ href: "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.0.4/css/bootstrap.min.css", rel: "stylesheet" }
    = stylesheet_link_tag    "application", :media => "all"

    = javascript_include_tag "application"
    %script{ type: "text/javascript", src: "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.0.4/bootstrap.min.js" }

    = csrf_meta_tags

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = link_to root_path, class: "brand" do
            = image_tag("1d-logo.png", alt: "1D Music", size: "16x16")
            1D Music

          - if user_signed_in?
            %ul.nav.pull-right
              %li.dropdown
                =link_to '#', class: 'dropdown-toggle', data: {dropdown: 'dropdown', toggle: 'dropdown'} do
                  #{current_user.first_name.titleize}
                  %i.icon-white.icon-chevron-down

                %ul.dropdown-menu
                  %li
                    =link_to root_path do
                      %i.icon-folder-open
                      My Library
                  .divider
                  %li
                    =link_to edit_registration_path(current_user) do
                      %i.icon-edit
                      Edit Account
                  .divider
                  %li
                    =link_to destroy_user_session_path, method: :delete do
                      %i.icon-off
                      Log Out


    .main-container
      = render "shared/flash_message"

      = yield